apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-prom-testing
  namespace: metrics-testing
  labels:
    app: nodejs-prom-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-prom-testing
  template:
    metadata:
      labels:
        app: nodejs-prom-testing
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
    spec:
      containers:
        - name: nodejs-prom-testing
          image: registry.gitlab.com/guidesmiths/chapters/devops/research/sample-nodejs-service-with-metrics
          envFrom:
            - secretRef:
                name: nodejs-prom-testing-secrets
          resources:
            limits:
              cpu: 125m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 4000
              name: metrics
          imagePullPolicy: Always
