image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - build-image
  - test
  - release-image
  - pages

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-image:
  stage: build-image
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE npm run test

release-image:
  stage: release-image
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main

pages:
  stage: pages
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -d --name load-testing-sample-api $CONTAINER_TEST_IMAGE
    - docker exec -i load-testing-sample-api npm run api-docs:create
    - docker cp load-testing-sample-api:/usr/src/app/docs/generated/jsdoc/. public
    - docker stop load-testing-sample-api
  artifacts:
    paths:
      - public